export const NAVIGATION = {
  CHANGE_ACTIVE_PATH: 'NAVIGATION.CHANGE_ACTIVE_PATH',
  SET_PAGE_LOADING: 'SET_PAGE_LOADING',
};

export const AUTH = {
  SET_DATA: 'AUTH.SET_DATA',
};

export const LOGIN = {
  SUCCESS: 'LOGIN.SUCCESS',
  LOADING: 'LOGIN.LOADING',
  RESET: 'LOGIN.RESET',
  FAIL: 'LOGIN.FAIL',
};

export const SIGNUP = {
  SUCCESS: 'SIGNUP.SUCCESS',
  LOADING: 'SIGNUP.LOADING',
  RESET: 'SIGNUP.RESET',
  FAIL: 'SIGNUP.FAIL',
};

export const RECOVERY_ACCOUNT_RESET = {
  SUCCESS: 'RECOVERY_ACCOUNT_RESET.SUCCESS',
  LOADING: 'RECOVERY_ACCOUNT_RESET.LOADING',
  FAIL: 'RECOVERY_ACCOUNT_RESET.FAIL',
  SET_DATA: 'RECOVERY_ACCOUNT_RESET.SET_DATA',
};

export const RECOVERY_ACCOUNT_CONFIRM_UPDATE = {
  SUCCESS: 'RECOVERY_ACCOUNT_CONFIRM_UPDATE.SUCCESS',
  LOADING: 'RECOVERY_ACCOUNT_CONFIRM_UPDATE.LOADING',
  FAIL: 'RECOVERY_ACCOUNT_CONFIRM_UPDATE.FAIL',
  SET_DATA: 'RECOVERY_ACCOUNT_CONFIRM_UPDATE.SET_DATA',
};

export const SETTINGS_UPDATE_EMAIL = {
  SUCCESS: 'SETTINGS_UPDATE_EMAIL.SUCCESS',
  LOADING: 'SETTINGS_UPDATE_EMAIL.LOADING',
  FAIL: 'SETTINGS_UPDATE_EMAIL.FAIL',
};

export const SETTINGS_UPDATE_PASSWORD = {
  SUCCESS: 'SETTINGS_UPDATE_PASSWORD.SUCCESS',
  LOADING: 'SETTINGS_UPDATE_PASSWORD.LOADING',
  FAIL: 'SETTINGS_UPDATE_PASSWORD.FAIL',
};

export const ACCOUNT_INFO = {
  SUCCESS: 'ACCOUNT_INFO.SUCCESS',
  LOADING: 'ACCOUNT_INFO.LOADING',
  FAIL: 'ACCOUNT_INFO.FAIL',
  SET_DATA: 'ACCOUNT_INFO.SET_DATA',
};

export const ACCOUNT_BALANCE = {
  SUCCESS: 'ACCOUNT_INFO.SUCCESS',
  LOADING: 'ACCOUNT_INFO.LOADING',
  FAIL: 'ACCOUNT_INFO.FAIL',
  SET_DATA: 'ACCOUNT_INFO.SET_DATA',
};
